name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore and Build
        run: |
          dotnet restore PhysicsFormulas/Source/PhysicsFormulas/PhysicsFormulas.csproj
          dotnet build --configuration Release PhysicsFormulas/Source/PhysicsFormulas/PhysicsFormulas.csproj
      - name: Test the project
        run: dotnet test PhysicsFormulas/Test/PhysicsFormulasUnitTests/PhysicsFormulasUnitTests.csproj
        run: dotnet test PhysicsFormulas/Source/PhysicsFormulas/PhysicsFormulas.csproj
      - name: publish to nuget
        env: 
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        run: |
          dotnet pack --configuration Release PhysicsFormulas/Source/PhysicsFormulas/PhysicsFormulas.csproj --output Nuget
          dotnet nuget push "Nuget/**.nupkg" --source "https://api.nuget.org/v3/index.json" --api-key ${NUGET_KEY}